name: Daily Commit

on:
  schedule:
    - cron: '10 5 * * *'  # Runs every day at 05:10 UTC
  workflow_dispatch:       # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make a small change
        run: |
          echo "Last run: $(date)" >> daily-log.txt

      - name: Commit change - 24f1000922@ds.study.iitm.ac.in
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Daily commit on $(date)" || echo "No changes to commit"
          git push
